export default {
  index: 'Introduction',
  guides: 'Guides',
  crypto: '@exortek/crypto',
  security: '@exortek/security',
  otp: '@exortek/otp',
  password: '@exortek/password',
  session: '@exortek/session',
  jwk: '@exortek/jwk',
  jws: '@exortek/jws',
  jwt: '@exortek/jwt',
  jwe: '@exortek/jwe',
  challenge: '@exortek/challenge',
  apikey: '@exortek/apikey',
  'magic-link': '@exortek/magic-link',
  jwks: '@exortek/jwks',
  ua: '@exortek/ua',
  opaque: '@exortek/opaque',
  passkey: '@exortek/passkey',
  paseto: '@exortek/paseto',
  comparison: 'Comparison',
  compliance: 'Compliance',
};
