export default {
  index: 'Introduction',
  crypto: '@exortek/crypto',
  security: '@exortek/security',
  otp: '@exortek/otp',
  password: '@exortek/password',
  session: '@exortek/session',
  jwk: '@exortek/jwk',
  jws: '@exortek/jws',
  jwt: '@exortek/jwt',
  challenge: '@exortek/challenge',
  apikey: '@exortek/apikey',
  'magic-link': '@exortek/magic-link',
  jwks: '@exortek/jwks',
  compliance: 'Compliance',
};
