import { BaseError } from '@exortek/shared/errors';

export const ErrorCode = Object.freeze({
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',

  // Challenge lifecycle
  CHALLENGE_MISMATCH: 'CHALLENGE_MISMATCH',
  CHALLENGE_EXPIRED: 'CHALLENGE_EXPIRED',
  CHALLENGE_ALREADY_USED: 'CHALLENGE_ALREADY_USED',
  CHALLENGE_INVALID: 'CHALLENGE_INVALID',

  // Client / authenticator data checks
  ORIGIN_MISMATCH: 'ORIGIN_MISMATCH',
  RP_ID_MISMATCH: 'RP_ID_MISMATCH',
  CLIENT_DATA_INVALID: 'CLIENT_DATA_INVALID',
  AUTH_DATA_INVALID: 'AUTH_DATA_INVALID',
  USER_VERIFICATION_REQUIRED: 'USER_VERIFICATION_REQUIRED',
  USER_PRESENCE_REQUIRED: 'USER_PRESENCE_REQUIRED',
  BACKUP_ELIGIBLE_REQUIRED: 'BACKUP_ELIGIBLE_REQUIRED',
  BACKED_UP_REQUIRED: 'BACKED_UP_REQUIRED',

  // Signature / crypto
  SIGNATURE_INVALID: 'SIGNATURE_INVALID',
  COUNTER_ROLLBACK: 'COUNTER_ROLLBACK',
  PUBLIC_KEY_UNSUPPORTED: 'PUBLIC_KEY_UNSUPPORTED',
  UNSUPPORTED_ALGORITHM: 'UNSUPPORTED_ALGORITHM',

  // Attestation
  ATTESTATION_INVALID: 'ATTESTATION_INVALID',
  ATTESTATION_TRUST_ANCHOR_MISSING: 'ATTESTATION_TRUST_ANCHOR_MISSING',
  UNSUPPORTED_ATTESTATION_FORMAT: 'UNSUPPORTED_ATTESTATION_FORMAT',

  // Extensions / MDS
  EXTENSION_INVALID: 'EXTENSION_INVALID',
  MDS_BLOB_INVALID: 'MDS_BLOB_INVALID',

  // Low-level decoding (CBOR / ASN.1 DER)
  DECODE_ERROR: 'DECODE_ERROR',
});

export class PasskeyError extends BaseError {
  static statuses = {
    [ErrorCode.INVALID_ARGUMENT]: 400,
    [ErrorCode.CHALLENGE_MISMATCH]: 400,
    [ErrorCode.CHALLENGE_EXPIRED]: 400,
    [ErrorCode.CHALLENGE_ALREADY_USED]: 400,
    [ErrorCode.CHALLENGE_INVALID]: 400,
    [ErrorCode.ORIGIN_MISMATCH]: 400,
    [ErrorCode.RP_ID_MISMATCH]: 400,
    [ErrorCode.CLIENT_DATA_INVALID]: 400,
    [ErrorCode.AUTH_DATA_INVALID]: 400,
    [ErrorCode.USER_VERIFICATION_REQUIRED]: 400,
    [ErrorCode.USER_PRESENCE_REQUIRED]: 400,
    [ErrorCode.BACKUP_ELIGIBLE_REQUIRED]: 400,
    [ErrorCode.BACKED_UP_REQUIRED]: 400,
    [ErrorCode.SIGNATURE_INVALID]: 400,
    [ErrorCode.COUNTER_ROLLBACK]: 400,
    [ErrorCode.PUBLIC_KEY_UNSUPPORTED]: 400,
    [ErrorCode.UNSUPPORTED_ALGORITHM]: 400,
    [ErrorCode.ATTESTATION_INVALID]: 400,
    [ErrorCode.ATTESTATION_TRUST_ANCHOR_MISSING]: 400,
    [ErrorCode.UNSUPPORTED_ATTESTATION_FORMAT]: 400,
    [ErrorCode.EXTENSION_INVALID]: 400,
    [ErrorCode.MDS_BLOB_INVALID]: 400,
    [ErrorCode.DECODE_ERROR]: 400,
  };
  static defaultStatus = 500;
}
